# Generated by Django 5.1.4 on 2024-12-27 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('imagem', models.FileField(upload_to='car/static/')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.brand_model')),
            ],
        ),
    ]
