# Generated by Django 5.1.4 on 2024-12-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_remove_car_model_imagem_car_model_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_model',
            name='imagem',
            field=models.ImageField(default=0, upload_to='static/media'),
            preserve_default=False,
        ),
    ]
